### ISSUE TITLE
Usar chat_data en lugar de user_data

### ISSUE THREAD

**Issue by FedeG** [PyAr/cuabot#5]
#### Motivo

Un mismo usuario podría mandar el comando de pregunta de diferentes chats y el `user_data` es el mismo para todas las conversaciones.
En cambio `chat_data` es uno para cada chat por ende el mismo usuario podría hablarle de distintos chats sin tener problema.

**Comment by aenima-x** [comment]
@FedeG  La idea original era que solo le pudieras preguntar directamente y no desde chats (creo que estaba el fixme en el codigo), de esa manera este cambio no era necesario.
Pero bueno si ya lo hiciste no habria drama
